# Generated by Django 2.1.2 on 2018-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
