# Generated by Django 2.1.2 on 2018-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0003_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='weight_per_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
