# Generated by Django 2.1.2 on 2018-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0005_auto_20181102_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(default='Amazing medicine'),
        ),
    ]
