# Generated by Django 2.1.2 on 2018-11-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0007_locationdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Item',
        ),
    ]
