# Generated by Django 2.1.2 on 2018-11-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0009_locationdata_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_per_unit',
            field=models.FloatField(),
        ),
    ]
