# Generated by Django 2.1.2 on 2018-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0010_auto_20181106_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
