# Generated by Django 2.1.2 on 2018-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0012_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/clinic_manager/imgs/Baxter Dextrose  NaCl 1000ml.JPG', upload_to='imgs'),
        ),
    ]
