# Generated by Django 2.1.2 on 2018-11-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0013_auto_20181118_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
