# Generated by Django 2.1.2 on 2018-11-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0014_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
