# Generated by Django 2.1.2 on 2018-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_processqueue_queue_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='processqueue',
            name='order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
