# Generated by Django 2.1.2 on 2018-11-21 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181118_0949'),
        ('warehouse', '0003_processqueue_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePersonnel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.User')),
            ],
            bases=('home.user',),
        ),
    ]
