# Generated by Django 2.1.2 on 2018-11-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dispatchqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatchQueue',
        ),
    ]
