# Generated by Django 2.1.2 on 2018-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_dispatchqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
    ]
