# Generated by Django 2.1.2 on 2018-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_dispatchqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchqueue',
            name='orders',
            field=models.TextField(default='{"orders": []}'),
        ),
    ]
