# Generated by Django 2.1.2 on 2018-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_dispatchqueue_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchqueue',
            name='orders',
        ),
        migrations.AddField(
            model_name='dispatchqueue',
            name='order_id',
            field=models.TextField(default='{"order_id": -1}'),
        ),
    ]
