# Generated by Django 2.1.2 on 2018-11-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_auto_20181106_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchqueue',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatchqueue',
            name='queue_number',
            field=models.IntegerField(),
        ),
    ]
