# Generated by Django 2.1.2 on 2018-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.UUIDField()),
                ('clientId', models.UUIDField(verbose_name='Client ID')),
                ('dateOrdered', models.DateTimeField(verbose_name='Date of Order')),
            ],
        ),
    ]
