# Generated by Django 2.1.2 on 2018-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0002_auto_20181030_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
