# Generated by Django 2.1.2 on 2018-11-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('clinic_manager', '0004_order_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.User')),
                ('order_cart', models.TextField(default='{}')),
            ],
            bases=('home.user',),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateOrdered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderStatus',
            new_name='order_status',
        ),
    ]
