# Generated by Django 2.1.2 on 2018-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0008_order_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmanager',
            name='clinic_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='order_clinic',
            field=models.TextField(default=''),
        ),
    ]
