# Generated by Django 2.1.2 on 2018-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0009_auto_20181102_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmanager',
            name='order_cart',
            field=models.TextField(default='"{}"'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contents',
            field=models.TextField(default='"{}"'),
        ),
    ]
