# Generated by Django 2.1.2 on 2018-11-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0013_auto_20181105_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contents',
            field=models.TextField(default='{"contents": []}'),
        ),
    ]
