# Generated by Django 2.1.2 on 2018-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0015_auto_20181106_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority_level',
            field=models.CharField(default='Low', max_length=200),
        ),
    ]
