# Generated by Django 2.1.2 on 2018-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0016_auto_20181117_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
