# Generated by Django 2.1.3 on 2018-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manager', '0017_auto_20181121_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority_level',
            field=models.IntegerField(default=2),
        ),
    ]
